server:
  port: 8080

spring:
  # Custom Config Import
  config:
    import:
      - classpath:/config/custom.yml
      - classpath:/config/custom-${spring.profiles.active:local}.yml
  # Devtools Config
  devtools:
    restart:
      enabled: false
  # Database Common Config
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false


# Logging Config
logging:
  level:
    com.example.demo: ERROR

# Swagger Config
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    groups-order: DESC
    operationsSorter: method
    disable-swagger-default-url: true
    display-request-duration: true
  api-docs:
    path: /api-docs
  show-actuator: true
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
