server:
  port: 8080

spring:
  profiles:
    active: dev
  # Custom Config Import
  config:
    import:
      - classpath:/config/custom/common.yml
      - classpath:/config/custom/${spring.profiles.active}.yml
      # logging
      - classpath:/config/logging/common.yml
      - classpath:/config/logging/${spring.profiles.active}.yml
      # DB
      - classpath:/config/db/common.yml
      - classpath:/config/db/${spring.profiles.active}.yml
      # swagger
      - classpath:/config/swagger/common.yml
      - classpath:/config/swagger/${spring.profiles.active}.yml
