spring:
  config:
    import:
      - classpath:/config/custom.yml
      - classpath:/config/custom-${spring.profiles.active:local}.yml
  devtools:
    restart:
      enabled: false

server:
  port: 8080

logging:
  level:
    com.example.demo: ERROR

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    groups-order: DESC
    operationsSorter: method
    disable-swagger-default-url: true
    display-request-duration: true
  api-docs:
    path: /api-docs
  show-actuator: true
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
