spring:
# Datasource Config
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
# JPA Config
  jpa:
    show-sql: false


# Swagger Config
springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false


  
