spring:
# H2 Database Config
  h2:
    console:
      enabled: true
      path: /h2
# Datasource Config
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password:
# JPA Config
  jpa:
    hibernate:
      ddl-auto: create-drop  # 개발환경에서만 사용
    properties:
      hibernate:
        format_sql: true
    show-sql: true


